### ISSUE TITLE
Doubt in Prediction (demo_binary.m)

### ISSUE THREAD

**Issue by sahil-prakash** [mehmetgonen/kbtl#1]
https://github.com/mehmetgonen/kbtl/blob/13d2460e8b424a75bf0f03368ac40b3f60bceda7/demo_binary.m#L54

Why do we need training samples for testing? (i.e why do we need similarity between training and testing data)

**Comment by mehmetgonen** [comment]
That is the main idea behind kernel methods since discriminant function is defined in terms of similarities between training and test samples.
